services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - my-local-network
    command: --bind-address=0.0.0.0

  pgsql:
    image: postgres:15
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - my-local-network

  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - my-local-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "9001:8081"
    networks:
      - my-local-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 512M
      PHP_INI_UPLOAD_MAX_FILESIZE: 100M
      PHP_INI_POST_MAX_SIZE: 100M
      PHP_INI_MEMORY_LIMIT: 512M
    ports:
      - "9002:80"
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
      - pgsql
    networks:
      - my-local-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: pgsql
    ports:
      - "9003:8080"
    depends_on:
      - mysql
      - pgsql
    networks:
      - my-local-network

volumes:
  mysql_data:
    driver: local
  pgsql_data:
    driver: local
    

networks:
  my-local-network:
    driver: bridge
