version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - wz-network
    command: --bind-address=0.0.0.0

  pgsql:
    image: postgres:15
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - wz-network

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass "Tw@bfYCNh@J2" --databases 16
    ports:
      - "6379:6379"
    networks:
      - wz-network
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: redis-manager
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379:2:Tw@bfYCNh@J2
  #   ports:
  #     - "8082:8082"
  #   networks:
  #     - wz-network

volumes:
  mysql_data:
    driver: local
  pgsql_data:
    driver: local

networks:
  wz-network:
    external: true
